"""empty message

Revision ID: 37da297d7473
Revises: 264b54508b54
Create Date: 2014-05-29 07:17:24.878132

"""

# revision identifiers, used by Alembic.
revision = '37da297d7473'
down_revision = '264b54508b54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(u'ix_follow_date_created', 'follow', ['date_created'], unique=False)
    op.create_index(u'ix_follow_username', 'follow', ['username'], unique=False)
    op.create_index(u'ix_like_date_created', 'like', ['date_created'], unique=False)
    op.create_index(u'ix_like_media_username', 'like', ['media_username'], unique=False)
    op.create_index(u'ix_like_username', 'like', ['username'], unique=False)
    op.create_index(u'ix_show_date_tagged', 'show', ['date_tagged'], unique=False)
    op.create_index(u'ix_show_hour_tagged', 'show', ['hour_tagged'], unique=False)
    op.create_index(u'ix_user_access_token', 'user', ['access_token'], unique=False)
    op.create_index(u'ix_user_date_created', 'user', ['date_created'], unique=False)
    op.create_index(u'ix_user_pic', 'user', ['pic'], unique=False)
    op.create_index(u'ix_user_username', 'user', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_user_username', table_name='user')
    op.drop_index(u'ix_user_pic', table_name='user')
    op.drop_index(u'ix_user_date_created', table_name='user')
    op.drop_index(u'ix_user_access_token', table_name='user')
    op.drop_index(u'ix_show_hour_tagged', table_name='show')
    op.drop_index(u'ix_show_date_tagged', table_name='show')
    op.drop_index(u'ix_like_username', table_name='like')
    op.drop_index(u'ix_like_media_username', table_name='like')
    op.drop_index(u'ix_like_date_created', table_name='like')
    op.drop_index(u'ix_follow_username', table_name='follow')
    op.drop_index(u'ix_follow_date_created', table_name='follow')
    ### end Alembic commands ###
